development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://eeuguqmybvlmmi:6d9d0dd525f936da023ff390f2fa1e755d4e7f1c3f00b4a537951f1db2c66c49@ec2-23-21-220-188.compute-1.amazonaws.com:5432/daa78ssr5rc15k
